#!/usr/bin/bash

source ~/Scripts/dwm/dwm_pango_defs

getInfoString()
{
    local ADP_STATUS="$(getADPStatus /sys/class/power_supply/ADP1)"
    local BAT_STATUS="$(getBatteryStatus /sys/class/power_supply/BAT0)"
    local VOL_STATUS="$(getVolumeStatus)"
    local ET0_STATUS="${SIGN_NET}$(getConnectionStatus eth0)"
    local ET1_STATUS="${SIGN_NET}$(getConnectionStatus eth1)"
    local BT0_STATUS="${SIGN_BLTT}$(getBluetoothStatus /sys/class/bluetooth/hci0/rfkill0)"
    local BKL_STATUS="$(getBacklightStatus)"
    echo -n -e " $(date) "
    echo -n -e "$(addSectionL " ${ADP_STATUS} ${SEP_L_LINE} ${BAT_STATUS} ")"
    echo -n -e "$(addSectionL " ${BT0_STATUS} ${SEP_L_LINE} ${ET0_STATUS} ${SEP_L_LINE} ${ET1_STATUS} ")"
    echo -n -e "$(addSectionL " ${BKL_STATUS} ${SEP_L_LINE} ${VOL_STATUS} ")"
}

