#!/bin/bash

TARGET_MAC="F4:6D:04:AE:EB:DB"
TARGET_ADDR="192.168.0.101"
TARGET_USER="daddona"
BROADCAST_ADDR="192.168.0.255"

function countdown
{
        local OLD_IFS="${IFS}"
        IFS=":"
        local ARR=( $1 )
        local SECONDS=$((  (ARR[0] * 60 * 60) + (ARR[1] * 60) + ARR[2]  ))
        local START=$(date +%s)
        local END=$((START + SECONDS))
        local CUR=$START

        while [[ $CUR -lt $END ]]
        do
                CUR=$(date +%s)
                LEFT=$((END-CUR))

                printf "\r%02d:%02d:%02d" \
                        $((LEFT/3600)) $(( (LEFT/60)%60)) $((LEFT%60))

                sleep 1
        done
        IFS="${OLD_IFS}"
        echo "        "
}

echo ""
echo "Turning on Daddona Central Server..."

wol -v -i "$BROADCAST_ADDR" "$TARGET_MAC" 

case "$1" in
	"wait")
    until ping -c1 -W1 ${TARGET_ADDR} &> /dev/null
    do
      echo -n "retrying in"
      conuntdown "00:00:08"
    done
    notify-email "[DDNet] Server is on-line" "Hi!\ndaddona-central-server is now running and on-line.\n\nBye bye!!"
		;;
	"login")
    echo "Waiting for Server to Boot: "
    ssh -Y "${TARGET_USER}@${TARGET_ADDR}"
		;;
  *)
    # ignore    
    ;;
esac
